from typing import Optional, Pattern, AnyStr, List, Type, Callable
from unittest import TestCase


class SolutionBase(object):
    NUMBER: int
    VERIFIED_ANSWER: Optional[int]
    SOLUTION_CLASS_NAME_RE: Pattern[AnyStr]
    SOLUTION_CLASS_SORT_KEY: Callable[[Type[SolutionBase]], Any]

    @property
    def url(self) -> str: ...
    def run_tests(self, test_case: TestCase) -> None: ...
    def get_answer(self) -> int: ...
    @staticmethod
    def get_solution_classes() -> List[Type[SolutionBase]]: ...
    @staticmethod
    def get_lines_from_data_file(filename: str) -> List[str]: ...
    def print_answer(self, run_tests: bool = True) -> None: ...
