from typing import Dict, Union


class SuDokuPuzzle(object):
    _values: Dict[str, str]
    def __init__(self, grid: str) -> SuDokuPuzzle: ...
    @staticmethod
    def parse_grid(grid: str) -> Union[Dict[str, str], bool]: ...
    @staticmethod
    def assign(values: Dict[str, str], square: str, digit: str) -> Union[Dict[str, str], bool]: ...
    @staticmethod
    def eliminate(values: Dict[str, str], square: str, digit: str) -> Union[Dict[str, str], bool]: ...
    @staticmethod
    def search(values: Dict[str, str]) -> Union[Dict[str, str], bool]: ...
    def solve(self) -> str: ...