from typing import Iterable, Any, Optional, Callable

def exactly_n(iterable: Iterable[Any], n: int) -> bool: ...
def first_true(iterable: Iterable[Any], default: Any = False, pred: Optional[Callable[[Any], bool]] = None) -> Any: ...
def str_product(a: Iterable[str], b: Iterable[str]) -> Iterable[str]: ...