from typing import Iterable, Any, Optional, Callable

def exactly_n(iterable: Iterable[Any], n: int) -> bool: ...
def first_true(iterable: Iterable[Any], default: Any = False, predicate: Optional[Callable[[Any], bool]] = None) -> Any: ...
def str_product(a: Iterable[str], b: Iterable[str]) -> Iterable[str]: ...
def flatten(iterable: Iterable[Any], max_depth: Optional[int] = None) -> Iterable[Any]: ...
