from typing import Iterator, Optional


def positive_integers() -> Iterator[int]: ...
def triangular_numbers(n: Optional[int] = None) -> Iterator[int]: ...
def squares() -> Iterator[int]: ...
def pentagonal_numbers() -> Iterator[int]: ...
def hexagonal_numbers() -> Iterator[int]: ...
def heptagonal_numbers() -> Iterator[int]: ...
def octagonal_numbers() -> Iterator[int]: ...
def ulams_spiral_diagonal_numbers() -> Iterator[int]: ...
def abundant_numbers() -> Iterator[int]: ...
def prime_numbers() -> Iterator[int]: ...
def prime_numbers_up_to(n: int) -> Iterator[int]: ...
